version: '3.3'
services:

  php72:
    image: ${PHP72_IMAGE}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    cap_add:
      - SYS_PTRACE
    volumes:
      # 挂载PHP核心配置文件
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini
      # 挂载php-fpm进程服务的配置文件
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.conf
      # 挂载php-fpm进程服务的扩展配置文件
      - ${PHP72_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      # 挂载seaslog
      - ${PHP72_SEASLOG_PATH}:/var/log/seaslog
      # 挂载慢日志
      - ${PHP72_SLOWLOG_PATH}:/var/log/slow
      # 挂载PHP项目到容器中PHP默认访问目录
      - ${WWW}:/var/www/html
    restart: always
    ports:
      # 开启容器内部9000端口，外部端口自动分配
      - '9000'
    networks:
      - default
    container_name: php72

  # web 服务器 nginx
  nginx:
    image: ${NGINX115_IMAGE}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    volumes:
        # 挂载本地nginx配置文件
        - ${NGINX115_NGINX_CONF_FILE}:/etc/nginx/nginx.conf
        # 挂载本地nginx 域名配置目录
        - ${NGINX115_NGINX_CONFD_DIR}:/etc/nginx/conf.d
        # 挂载本地SSL证书目录
        - ${NGINX115_NGINX_CERT_DIR}:/etc/nginx/cert
        # 挂载本地日志目录
        - ${NGINX115_NGINX_LOG_DIR}:/var/log/nginx
        # 挂载本地项目目录
        - ${WWW}:/usr/share/nginx/html
    restart: always
    ports:
      - '80:80'
    networks:
      - default
    container_name: nginx

  mysql8:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql8
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - ${MYSQL_CONF_FILE}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR}:/var/lib/mysql/:rw
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: "$TZ"

  mysql8.0.23:
    container_name: mysql8.0.23
    image: mysql:${MYSQL_VERSION_1}
    ports:
      - "3306"
    volumes:
      - ${MYSQL_CONF_FILE_1}:/etc/mysql/conf.d/mysql.cnf:ro
      - ${MYSQL_DATA_DIR_1}:/var/lib/mysql/:rw
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD_1}
      TZ: "$TZ"

  redis:
    image: registry.cn-beijing.aliyuncs.com/rdisme/redis:5-0
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    ports:
      - "6379"
    volumes:
      - ./redis/redis.conf/:/usr/local/etc/redis.conf
      - ./redis/data:/usr/local/redis/data
    networks:
      - default
    restart: always
    container_name: redis

  # 消息中间件
  rabbitmq:
    image: ${RABBITMQ38_IMAGE}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    hostname: ${RABBITMQ38_HOSTNAME}
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ38_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ38_WEB_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ38_WEB_PWD}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ38_WEB_VHOST}
    ports:
      # web后台 端口
      - "15672:15672"
      - "5672"
    networks:
      - default
    restart: always
    container_name: rabbitmq

  activemq:
    image: rmohr/activemq
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    ports:
      # activemq服务监控端口
      - "5672:61613"
      # web管理页面端口
      - "8161:8161"
    networks:
      - default
    restart: always
    container_name: activemq

  php-supervisor:
    image: ${PHP72_IMAGE}
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "20"
    cap_add:
      - SYS_PTRACE
    volumes:
      # 挂载PHP核心配置文件
      - ${PHP72_PHP_CONF_FILE}:/usr/local/etc/php/php.ini
      # 挂载php-fpm进程服务的配置文件
      - ${PHP72_FPM_CONF_FILE}:/usr/local/etc/php-fpm.conf
      # 挂载php-fpm进程服务的扩展配置文件
      - ${PHP72_WWW_CONF_FILE}:/usr/local/etc/php-fpm.d/www.conf
      # 挂载seaslog
      - ${PHP72_SEASLOG_PATH}:/var/log/seaslog
      # 挂载慢日志
      - ${PHP72_SLOWLOG_PATH}:/var/log/slow
      # 挂载PHP项目到容器中PHP默认访问目录
      - ${WWW}:/var/www/html
      # 挂载supervisor配置文件
      - ${SUPERVISOR_CONF_DIR}:/etc/supervisor
    ports:
      # supervisor web管理后台端口映射
      - 9001:9001
    networks:
      - default
    restart: always
    command: supervisord -nc /etc/supervisor/supervisord.conf
    container_name: php-supervisor

  phpredisadmin:
    image: erikdubbelboer/phpredisadmin:latest
    ports:
      - "${REDISMYADMIN_HOST_PORT}:80"
    environment:
      - REDIS_1_HOST=redis
      - REDIS_1_PORT=6379
      - TZ=$TZ
    networks:
      - default
    container_name: phpredisadmin

  # mysql admin
  adminer:
    image: adminer
    restart: always
    depends_on:
      - mysql8.0.23
    ports:
      - 8090:8080
    networks:
      - default
    container_name: adminer

  # mysql admin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql8
    ports:
      - "${PHPMYADMIN_HOST_PORT}:80"
    volumes:
      - ${PHPMYADMIN_USER_CONF_FILE}:/etc/phpmyadmin/config.user.inc.php:ro
      - ${PHPMYADMIN_PHP_CONF_FILE}:/usr/local/etc/php/conf.d/php-phpmyadmin.ini:ro
    environment:
      - PMA_HOST=mysql8
      - PMA_PORT=3306
      - TZ=$TZ
    networks:
      - default
    container_name: phpmyadmin


networks:
  default: